const mostrarModelos=[]

agregarNuevosModelos()

mostrarModelos.push(new modelos(`../multimedia/imagenes/c905c18a-9baf-49eb-909b-73dd247670f5.jpg`,`FERRARI 488 SPIDER`,`FERRARI`,`El Ferrari 488 es un automóvil superdeportivo de dos puertas biplaza, con motor central-trasero montado longitudinalmente y de tracción trasera, producido por el fabricante italiano Ferrari.<br>
El primero en ser introducido fue el 488 GTB berlinetta, para reemplazar al anterior 458 Italia como su sucesor. Se lanzó el 3 de febrero de 2015, antes de su estreno mundial en el Salón del Automóvil de Ginebra en marzo de ese mismo año.`,436,850,`<img src="../multimedia/imagenes/Scuderia_Ferrari_(cropped).png">`,6,""))
mostrarModelos.push(new modelos(`../multimedia/imagenes/ferrari-roma.jpg`, `FERRARI ROMA`,`FERRARI`,`El Ferrari Roma es un deportivo de motor V8 Biturbo delantero, fabricado por Ferrari y que rinde 620 CV. Se trata de un modelo desarrollado como coupé, que no contará con carrocería descapotable ya que su alternativa para tal fin será el Ferrari Portofino. Su planteamiento es el de un deportivo de tintes Gran Turismo, ofreciendo un nivel alto en tanto a prestaciones, pero sin olvidarse del confort o la practicidad con una configuración del habitáculo con 2+2 asientos. Su fabricación, como sucede con todos los modelos Ferrari, se realiza en la planta que posee la firma en Maranello, Italia.
<br>
El Ferrari Roma cuenta como principal rival al Aston Martin DB11 V8, con el que comparte planteamiento y configuración mecánica, y el Bentey Continental GT V8, modelo que también ofrece una configuración mecánica muy similar. Otros rivales cercanos por su carácter GT son el Porsche 911 Turbo y el McLaren GT, si bien ambos emplean configuraciones técnicas muy dispares. No te pierdas nuestra guía de compra con los mejores deportivos actualmente en el mercado.`,547,200,`<img src="../multimedia/imagenes/Scuderia_Ferrari_(cropped).png">`,5,""))
mostrarModelos.push(new modelos(`../multimedia/imagenes/Lamborghini_Huracan_STO09_0.webp`,`LAMBORGHINI HURACAN`,`LAMBORGHINI`,`El Lamborghini Huracán es el acuerdo ideal entre tecnología y diseño. 
La primera emoción se siente con solo mirarlo. Líneas definidas y aerodinámicas diseñadas para contrarrestar el aire y domar la carretera. La segunda se experimenta al tocarlo. Se emplean las mejores habilidades artesanales italianas para la elaboración de acabados de prestigio y calidad sin precedentes. La tercera emoción se experimenta al pulsar el botón de encendido y sentir el motor V10 de aspiración natural y toda la tecnología necesaria para controlarlo. La última emoción proviene del sistema de iluminación full LED y el salpicadero con TFT de 12,3'', para una experiencia de conducción incomparable.`,958,480,`<img src="../multimedia/imagenes/lamborghini.jpg">`,3,""))
mostrarModelos.push(new modelos(`../multimedia/imagenes/aventador.jpg`,`LAMBORGHINI AVENTADOR`,`LAMBORGHINI`,`El Lamborghini Aventador es un automóvil superdeportivo biplaza de dos puertas de tijera, con motor central-trasero montado longitudinalmente y tracción en las cuatro ruedas, producido por el fabricante italiano Lamborghini, filial del Grupo Volkswagen. Fue concebido para reemplazar al Murciélago, como el nuevo modelo tope de gama.`,253,550,`<img src="../multimedia/imagenes/lamborghini.jpg">`,2,""))
mostrarModelos.push(new modelos(`../multimedia/imagenes/NAZ_7a2d67b544004dbb8350c1fa34990a73.webp`,`BUGATTI CHIRON`,`BUGATTI`,`El Bugatti Chiron es un automóvil superdeportivo coupé de 2 puertas biplaza, con motor central-trasero montado longitudinalmente y de tracción integral, diseñado y desarrollado por Bugatti Automobiles S.A.S., filial del Grupo Volkswagen. Fue presentado en el Salón del Automóvil de Ginebra 2016 como el sucesor del Bugatti Veyron.4​Su producción está limitada a 500 unidades, de las cuales 120 ya habían sido vendidas a un precio de 2 400 000 de € como mínimo sin contar impuestos, es decir, alrededor de 1 900 000 de £ o US$2 900 000 ($3 127 191 en 2022) cada una.5​`,476,950,`<img src="../multimedia/imagenes/800px-Bugatti_Logo.png">`,4,""))
mostrarModelos.push(new modelos(`../multimedia/imagenes/16152842503708.jpg`,`BUGATTI DIVO`,`BUGATTI`,`El Bugatti Divo es un automóvil superdeportivo coupé de dos puertas biplaza, con motor central-trasero montado longitudinalmente y tracción en las cuatro ruedas, desarrollado y producido desde 2019 por el fabricante Bugatti Automobiles S.A.S., filial del Grupo Volkswagen.

Su nombre es un homenaje al piloto de carreras francés Albert Divo, quien corrió para Bugatti en la década de 1920, venciendo dos veces en la carrera Targa Florio.3​`,965,950,`<img src="../multimedia/imagenes/800px-Bugatti_Logo.png">`,5,""))



const nuevoCarrito=[]

